name: leafy_guardian
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  go_router: ^13.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.4.2+1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  glass: ^2.0.0+1
  swipable_stack: ^2.0.0
  supabase_flutter: ^2.5.1
  awesome_snackbar_content: ^0.1.3
  huggingface_dart: ^0.0.2
  google_generative_ai: ^0.3.3
  lottie: ^3.1.0
  image_picker: ^1.1.1
  camera: ^0.10.6
  permission_handler: ^11.3.1
  numberpicker: ^2.1.2
  flutter_animate: ^4.5.0
  location: ^6.0.2
  geocoding: ^3.0.0
  carousel_slider: ^4.2.1
  image: ^4.2.0
  path_provider:
  background_remover: ^0.0.3
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/  
    - assets/icons/  
